In [1]:
import numpy as np
import pandas as pd

In [2]:
#Creating a Dataframe

In [10]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [11]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [15]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2=pd.DataFrame(data_list)
columns=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [13]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [18]:
# Selection and Indexing of column

In [19]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [22]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [24]:
#creating a new column

In [25]:
df2["Designation"]=["Doctor","Engg.","Doctor","Engg"]

In [26]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000       Engg.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Engg

In [39]:
##remove a column

In [40]:
df2.drop(0,axis=0)

    Name  Age
1   Anna   34
2  Peter   29
3  Linda   42

In [41]:
#selecting row

In [46]:
df2.loc[[0,1]]

   Name  Age
0  John   28
1  Anna   34

In [47]:
df2.iloc[3]

Name    Linda
Age        42
Name: 3, dtype: object

In [48]:
#selecting Subsets of rows and columns

In [49]:
df2.loc[[0,1]][["Name","Age"]]

   Name  Age
0  John   28
1  Anna   34

In [50]:
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [51]:
#conditional selection

In [52]:
df2

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [53]:
#i only want to see people whose age is above 30

In [54]:
df2[df2["Age"]>30]

    Name  Age
1   Anna   34
3  Linda   42

In [55]:
#I only want people whose age is above 30 and there name is linda

In [56]:
df2[(df2["Age"]>30) &(df2["Name"]=='Linda')]

    Name  Age
3  Linda   42